services:
    admin.category:
        class: CoreBundle\Admin\CategoryAdmin
        arguments: [~, ECommerceBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Catégories, group: Vente }
    admin.product:
        class: CoreBundle\Admin\ProductAdmin
        arguments: [~, ECommerceBundle\Entity\Product, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Produits, group: Vente }
    admin.order:
        class: CoreBundle\Admin\OrderAdmin
        arguments: [~, ECommerceBundle\Entity\Order, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Commandes, group: Vente }