user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

e_commerce:
    resource: "@ECommerceBundle/Controller/"
    type:     annotation
    prefix:   /

core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

# Lexik Paybox Bundle
lexik_paybox:
    resource: '@LexikPayboxBundle/Resources/config/routing.yml'

_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /admin