# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    lexik_paybox.response_listener.class: 'ECommerceBundle\Listener\PaymentListener'

services:
    user.uploader:
        class: ECommerceBundle\Services\Uploader
        arguments: ['%upload_directory%']

    user.doctrine_uploader_listener:
        class: ECommerceBundle\Listener\UploadListener
        arguments: ['@user.uploader']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    lexik_paybox.response_listener:
        class: '%lexik_paybox.response_listener.class%'
        arguments: [ '%kernel.root_dir%', '@filesystem' ]
        tags:
            - { name: kernel.event_listener, event: paybox.ipn_response, method: onPayboxIpnResponse }