# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    user.uploader:
        class: ECommerceBundle\Services\Uploader
        arguments: ['%upload_directory%']

    user.doctrine_uploader_listener:
        class: ECommerceBundle\Listener\UploadListener
        arguments: ['@user.uploader']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }